### PR TITLE
Update GettingStartedWithFPSection.scala

### PR DESCRIPTION
**Pull request by slashdev1**
I think function `isSorted` has a mistake because `isSorted(Array(1, 3, 5, 7), (x: Int, y: Int) => x > y)` should be return false:
in the first step condition `1 > 3` is `false`

### CODE REVIEW

**Comment by FRosner** [comment]
Hi! Thanks for the contribution. It is confusing to me indeed why the higher order function, which is the sorted condition, is negated in the current implementation. If you are modifying the logic however you either need to invert all the conditions in the exercises or change the expected values in https://github.com/scala-exercises/exercises-fpinscala/blob/master/src/test/scala/fpinscalalib/GettingStartedWithFPSpec.scala#L24

**Comment by slashdev1** [comment]
Hi. Thanks for the answer. How do you mean it is good idea if I'll change conditions signs in `isSortedAssert`: `>` to `<` and `<` to `>`

**Comment by FRosner** [comment]
I think that makes sense but maybe I'm not getting what the method is supposed to do. Can you find out the original author and ping them here?

**Comment by slashdev1** [comment]
Hello @jdesiloniz Can you read my previous post and answer it.

**Comment by jdesiloniz** [comment]
@slashdev1 @FRosner Hello, and thanks for this PR! I think I added that negation by mistake while writing that exercise. I'd move forward with your PR if no one has any objections! 👍

**Comment by FRosner** [comment]
We should fix the test I guess? We can't just change the code without changing the test, or?

**Comment by jdesiloniz** [comment]
@FRosner Yeah, fixed this in the following PR: https://github.com/scala-exercises/exercises-fpinscala/pull/46. Unfortunately the issues that we had with Travis and the JDK masked the test problems.

**Comment by vgrigoriu** [comment]
I think the original implementation is correct. If `as(n)` and `as(n + 1)` are _not_ ordered, then the whole sequence is not ordered. I think `isOrdered(Array(1, 2, 3), (x: Int, y: Int) => x <= y)` should be true and `isOrdered(Array(1, 2, 3), (x: Int, y: Int) => x > y)` should be false.

**Pull request merged**
